# Enable split keyboard support for passing indicator state to peripherals	
CONFIG_ZMK_HID_INDICATORS=y
CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y


CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_COMBO_TIMEOUT_MS=25

CONFIG_ZMK_POINTING_BLOCK_WHILE_CLICK=n
